name: "Maintenance Window Validator"
description: "A custom GitHub Action to verify if the current time falls within a specified maintenance window."
inputs:
  start_time:
    description: "Start time of the maintenance window (in 24-hour format)."
    required: true
    default: "0"
  end_time:
    description: "End time of the maintenance window (in 24-hour format)."
    required: true
    default: "6"
outputs:
  is_within_time_range:
    description: "Indicates whether the current time falls within the maintenance window (true/false)."
runs:
  using: "node16"
  main: "index.js"
