name: "Age Check Action"
description: "Checks if the user's age is above 18 and proceeds only if eligible."
inputs:
  age:
    description: "The age of the user."
    required: true
runs:
  using: "node16"
  main: "index.js"
