name: Time Check Workflow

on:
  workflow_dispatch:
    inputs:
      start_time:
        description: "Enter the start time (24-hour format, e.g., 0 for 12 AM)"
        required: true
        default: "0"
      end_time:
        description: "Enter the end time (24-hour format, e.g., 6 for 6 AM)"
        required: true
        default: "6"

jobs:
  time-check:
    runs-on: ubuntu-latest
    steps:
      - name: Time Check Step
        uses: mr-7v/test-customActions@main
        with:
          start_time: "${{ github.event.inputs.start_time }}"
          end_time: "${{ github.event.inputs.end_time }}"

